# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('contract_type', models.CharField(choices=[('new', 'New business'), ('renewal', 'Renewal'), ('amendment', 'Amendment'), ('nda', 'NDA'), ('msa', 'Master service agreement'), ('sow', 'Statement of work')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('sent', 'Sent'), ('signed', 'Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_contracts', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('clause_type', models.CharField(choices=[('payment', 'Payment terms'), ('liability', 'Liability'), ('termination', 'Termination'), ('sla', 'Service level'), ('confidentiality', 'Confidentiality'), ('renewal', 'Renewal'), ('ip', 'Intellectual property')], default='payment', max_length=20)),
                ('status', models.CharField(choices=[('standard', 'Standard'), ('redlined', 'Redlined'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='standard', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_contractclauses', to='core.tenant')),
            ],
            options={
                'ordering': ['title', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('obligation_type', models.CharField(choices=[('deliverable', 'Deliverable'), ('payment', 'Payment'), ('reporting', 'Reporting'), ('sla', 'Service level'), ('compliance', 'Compliance'), ('renewal_notice', 'Renewal notice')], default='deliverable', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('met', 'Met'), ('missed', 'Missed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_contractobligations', to='core.tenant')),
            ],
            options={
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RenewalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('renewed', 'Renewed'), ('churned', 'Churned'), ('at_risk', 'At risk')], default='upcoming', max_length=20)),
                ('renewal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('proposed_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notice_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_renewalschedules', to='core.tenant')),
            ],
            options={
                'ordering': ['renewal_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('metric_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(choices=[('calls', 'API calls'), ('seats', 'Seats'), ('gb', 'Gigabytes'), ('hours', 'Hours'), ('units', 'Units')], default='units', max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('period_label', models.CharField(max_length=60)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_usagerecords', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='ctr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'contract_type'], name='ctr_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'start_date'], name='ctr_tenant_startdate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['tenant', 'status'], name='ccl_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['tenant', 'clause_type'], name='ccl_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['tenant', 'contract'], name='ccl_tenant_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='contractobligation',
            index=models.Index(fields=['tenant', 'status'], name='cob_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contractobligation',
            index=models.Index(fields=['tenant', 'obligation_type'], name='cob_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contractobligation',
            index=models.Index(fields=['tenant', 'contract'], name='cob_tenant_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalschedule',
            index=models.Index(fields=['tenant', 'status'], name='rsc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalschedule',
            index=models.Index(fields=['tenant', 'renewal_date'], name='rsc_tenant_rendate_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalschedule',
            index=models.Index(fields=['tenant', 'contract'], name='rsc_tenant_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tenant', 'unit'], name='usg_tenant_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tenant', 'recorded_on'], name='usg_tenant_recdate_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tenant', 'contract'], name='usg_tenant_contract_idx'),
        ),
    ]
