# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('partner_type', models.CharField(choices=[('reseller', 'Reseller'), ('referral', 'Referral'), ('oem', 'OEM'), ('system_integrator', 'System Integrator'), ('distributor', 'Distributor'), ('msp', 'Managed Service Provider')], default='reseller', max_length=20)),
                ('tier', models.CharField(choices=[('registered', 'Registered'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='registered', max_length=20)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('churned', 'Churned')], default='prospect', max_length=20)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('onboarded_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_partners', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DealRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('deal_name', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('won', 'Won')], default='submitted', max_length=20)),
                ('registered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_dealregistrations', to='core.tenant')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_registrations', to='partners.partner')),
            ],
            options={
                'ordering': ['-registered_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('conflict_type', models.CharField(choices=[('overlap', 'Overlap'), ('pricing', 'Pricing'), ('territory', 'Territory'), ('account_ownership', 'Account Ownership'), ('lead_dispute', 'Lead Dispute')], default='overlap', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('reported_on', models.DateField(default=django.utils.timezone.localdate)),
                ('resolution', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_channelconflicts', to='core.tenant')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='partners.partner')),
            ],
            options={
                'ordering': ['-reported_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('playbook', 'Playbook'), ('pricing', 'Pricing'), ('training', 'Training'), ('logo', 'Logo'), ('contract', 'Contract')], default='datasheet', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('internal', 'Internal')], default='partner', max_length=20)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral', to='partners.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_partnercollaterals', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=60)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deals_closed', models.IntegerField(default=0)),
                ('quota', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attainment', models.DecimalField(decimal_places=2, default=0, help_text='Attainment against quota as a percentage.', max_digits=6)),
                ('certification_count', models.IntegerField(default=0)),
                ('satisfaction_score', models.DecimalField(decimal_places=2, default=0, help_text='Partner satisfaction score, e.g. 4.50 out of 5.', max_digits=4)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='partners.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_partnerperformances', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'status'], name='prt_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'partner_type'], name='prt_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'tier'], name='prt_tenant_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='dealregistration',
            index=models.Index(fields=['tenant', 'status'], name='dreg_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dealregistration',
            index=models.Index(fields=['tenant', 'partner'], name='dreg_tenant_partner_idx'),
        ),
        migrations.AddIndex(
            model_name='dealregistration',
            index=models.Index(fields=['tenant', 'registered_on'], name='dreg_tenant_regdate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealregistration',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='channelconflict',
            index=models.Index(fields=['tenant', 'status'], name='cconf_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='channelconflict',
            index=models.Index(fields=['tenant', 'severity'], name='cconf_tenant_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='channelconflict',
            index=models.Index(fields=['tenant', 'conflict_type'], name='cconf_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelconflict',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='partnercollateral',
            index=models.Index(fields=['tenant', 'asset_type'], name='pcol_tenant_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercollateral',
            index=models.Index(fields=['tenant', 'access_level'], name='pcol_tenant_access_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercollateral',
            index=models.Index(fields=['tenant', 'partner'], name='pcol_tenant_partner_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerperformance',
            index=models.Index(fields=['tenant', 'partner'], name='pperf_tenant_partner_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerperformance',
            index=models.Index(fields=['tenant', 'recorded_on'], name='pperf_tenant_recdate_idx'),
        ),
    ]
