# Generated by Django 5.1.15 on 2026-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['tenant', 'status'], name='fulfil_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['tenant', 'order'], name='fulfil_tenant_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderamendment',
            index=models.Index(fields=['tenant', 'status'], name='amend_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderamendment',
            index=models.Index(fields=['tenant', 'order'], name='amend_tenant_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['tenant', 'order'], name='orderline_tenant_order_idx'),
        ),
    ]
