# Generated by Django 5.1.15 on 2026-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['tenant', 'opportunity'], name='competitor_tenant_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['tenant', 'status'], name='competitor_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dealcollaborator',
            index=models.Index(fields=['tenant', 'opportunity'], name='dealcollab_tenant_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='dealcollaborator',
            index=models.Index(fields=['tenant', 'status'], name='dealcollab_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityactivity',
            index=models.Index(fields=['tenant', 'opportunity'], name='oppact_tenant_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityactivity',
            index=models.Index(fields=['tenant', 'activity_type'], name='oppact_tenant_type_idx'),
        ),
    ]
