# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('erp', 'ERP'), ('marketing', 'Marketing automation'), ('communication', 'Communication'), ('bi', 'Business intelligence'), ('esignature', 'E-signature'), ('crm', 'CRM'), ('storage', 'Storage')], default='erp', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('configuring', 'Configuring')], default='disconnected', max_length=20)),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth 2.0'), ('api_key', 'API key'), ('basic', 'Basic auth'), ('token', 'Bearer token')], default='oauth', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations_connectors', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], default='inbound', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('paused', 'Paused')], default='scheduled', max_length=20)),
                ('schedule', models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('realtime', 'Real-time')], default='daily', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='integrations.connector')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations_syncjobs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('records_affected', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.syncjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations_synclogs', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('target_url', models.URLField(blank=True)),
                ('event_type', models.CharField(choices=[('record.created', 'Record created'), ('record.updated', 'Record updated'), ('record.deleted', 'Record deleted'), ('sync.completed', 'Sync completed'), ('error', 'Error')], default='record.created', max_length=30)),
                ('http_method', models.CharField(choices=[('post', 'POST'), ('put', 'PUT'), ('patch', 'PATCH')], default='post', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed')], default='active', max_length=20)),
                ('secret', models.CharField(blank=True, max_length=128)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations_webhooks', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.CharField(blank=True, max_length=64)),
                ('key_prefix', models.CharField(blank=True, max_length=12)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox'), ('development', 'Development')], default='sandbox', max_length=20)),
                ('scopes', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations_apikeys', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='akey_tenant_status_idx'), models.Index(fields=['tenant', 'environment'], name='akey_tenant_env_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['tenant', 'status'], name='conn_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['tenant', 'category'], name='conn_tenant_category_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant', 'status'], name='sjob_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant', 'connector'], name='sjob_tenant_connector_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncjob',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['tenant', 'level'], name='slog_tenant_level_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['tenant', 'job'], name='slog_tenant_job_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['tenant', 'status'], name='whk_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['tenant', 'event_type'], name='whk_tenant_event_idx'),
        ),
    ]
