# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=150)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('missed', 'Missed')], default='outbound', max_length=20)),
                ('call_type', models.CharField(choices=[('sales', 'Sales'), ('follow_up', 'Follow-up'), ('support', 'Support'), ('cold_call', 'Cold call')], default='sales', max_length=20)),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('voicemail', 'Voicemail'), ('no_answer', 'No answer'), ('busy', 'Busy'), ('scheduled_callback', 'Scheduled callback')], default='connected', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('call_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_callactivities', to='core.tenant')),
            ],
            options={
                'ordering': ['-call_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'direction'], name='call_tenant_direction_idx'), models.Index(fields=['tenant', 'outcome'], name='call_tenant_outcome_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('rep_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=150)),
                ('visit_type', models.CharField(choices=[('sales_call', 'Sales call'), ('demo', 'Demo'), ('check_in', 'Check-in'), ('support', 'Support'), ('prospecting', 'Prospecting')], default='sales_call', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No show')], default='planned', max_length=20)),
                ('scheduled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_fieldvisits', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='fvisit_tenant_status_idx'), models.Index(fields=['tenant', 'visit_type'], name='fvisit_tenant_type_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MobileAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('alert_type', models.CharField(choices=[('deal_update', 'Deal update'), ('task_due', 'Task due'), ('quota_warning', 'Quota warning'), ('approval_request', 'Approval request'), ('system', 'System')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='unread', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_mobilealerts', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='malert_tenant_status_idx'), models.Index(fields=['tenant', 'priority'], name='malert_tenant_priority_idx'), models.Index(fields=['tenant', 'alert_type'], name='malert_tenant_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=120)),
                ('user_name', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='ios', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost'), ('wiped', 'Wiped')], default='active', max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('push_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_mobiledevices', to='core.tenant')),
            ],
            options={
                'ordering': ['device_name', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='mdev_tenant_status_idx'), models.Index(fields=['tenant', 'platform'], name='mdev_tenant_platform_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('rep_name', models.CharField(max_length=120)),
                ('customer_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('submitted_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_mobilequotes', to='core.tenant')),
            ],
            options={
                'ordering': ['-submitted_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='mquote_tenant_status_idx'), models.Index(fields=['tenant', 'submitted_on'], name='mquote_tenant_subdate_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
