# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('plan_type', models.CharField(choices=[('flat', 'Flat rate'), ('tiered', 'Tiered'), ('accelerator', 'Accelerator'), ('bonus', 'Bonus / SPIFF')], default='flat', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission rate as a percentage, e.g. 5.00 for 5%.', max_digits=6)),
                ('target_quota', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_commissionplans', to='core.tenant')),
            ],
            options={
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('rep_name', models.CharField(max_length=150)),
                ('deal_reference', models.CharField(blank=True, max_length=120)),
                ('deal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('earned_on', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='compensation.commissionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_earnings', to='core.tenant')),
            ],
            options={
                'ordering': ['-earned_on', '-id'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Clawback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=150)),
                ('reason', models.CharField(choices=[('cancellation', 'Deal cancellation'), ('refund', 'Customer refund'), ('chargeback', 'Chargeback'), ('correction', 'Data correction'), ('other', 'Other')], default='cancellation', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('applied', 'Applied'), ('waived', 'Waived'), ('disputed', 'Disputed')], default='open', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_on', models.DateField(default=django.utils.timezone.localdate)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_clawbacks', to='core.tenant')),
                ('earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clawbacks', to='compensation.earning')),
            ],
            options={
                'ordering': ['-effective_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalPlanVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('AUD', 'Australian Dollar (AUD)'), ('CAD', 'Canadian Dollar (CAD)'), ('INR', 'Indian Rupee (INR)')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('retired', 'Retired')], default='active', max_length=20)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1, help_text='Exchange rate to the base (USD) currency.', max_digits=12)),
                ('local_quota', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Percentage point adjustment to the base rate.', max_digits=6)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='compensation.commissionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_globalplanvariations', to='core.tenant')),
            ],
            options={
                'ordering': ['region', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('rep_name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('payroll', 'Payroll system'), ('bank_transfer', 'Bank transfer'), ('check', 'Check'), ('wallet', 'Digital wallet')], default='payroll', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_label', models.CharField(blank=True, max_length=60)),
                ('scheduled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_payouts', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_on', '-id'],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
