# Generated by Django 5.1.15 on 2026-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clawback',
            index=models.Index(fields=['tenant', 'status'], name='claw_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clawback',
            index=models.Index(fields=['tenant', 'reason'], name='claw_tenant_reason_idx'),
        ),
        migrations.AddIndex(
            model_name='clawback',
            index=models.Index(fields=['tenant', 'effective_on'], name='claw_tenant_effdate_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['tenant', 'status'], name='cplan_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['tenant', 'plan_type'], name='cplan_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['tenant', 'effective_from'], name='cplan_tenant_effdate_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['tenant', 'status'], name='earn_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['tenant', 'plan'], name='earn_tenant_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['tenant', 'earned_on'], name='earn_tenant_earndate_idx'),
        ),
        migrations.AddIndex(
            model_name='globalplanvariation',
            index=models.Index(fields=['tenant', 'status'], name='gpv_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='globalplanvariation',
            index=models.Index(fields=['tenant', 'currency'], name='gpv_tenant_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='globalplanvariation',
            index=models.Index(fields=['tenant', 'plan'], name='gpv_tenant_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant', 'status'], name='pay_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant', 'method'], name='pay_tenant_method_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant', 'scheduled_on'], name='pay_tenant_scheddate_idx'),
        ),
    ]
