# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('field_key', models.CharField(max_length=60)),
                ('object_type', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('account', 'Account'), ('contact', 'Contact'), ('quote', 'Quote'), ('order', 'Order'), ('product', 'Product')], default='lead', max_length=20)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('dropdown', 'Dropdown'), ('currency', 'Currency'), ('url', 'URL')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=150)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterdata_customfields', to='core.tenant')),
            ],
            options={
                'ordering': ['object_type', 'name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='cfld_tenant_status_idx'), models.Index(fields=['tenant', 'object_type'], name='cfld_tenant_object_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('language_name', models.CharField(max_length=60)),
                ('locale', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('date_format', models.CharField(blank=True, max_length=40)),
                ('number_format', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterdata_localizationsettings', to='core.tenant')),
            ],
            options={
                'ordering': ['language_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='locz_tenant_status_idx'), models.Index(fields=['tenant', 'language_code'], name='locz_tenant_langcode_idx')],
            },
        ),
        migrations.CreateModel(
            name='MethodologyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('methodology', models.CharField(choices=[('meddic', 'MEDDIC'), ('bant', 'BANT'), ('spin', 'SPIN Selling'), ('challenger', 'Challenger Sale'), ('sandler', 'Sandler'), ('custom', 'Custom')], default='bant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('stages_count', models.IntegerField(default=5)),
                ('qualification_fields', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterdata_methodologyconfigs', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='mcfg_tenant_status_idx'), models.Index(fields=['tenant', 'methodology'], name='mcfg_tenant_method_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterdata_pricebooks', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='pbk_tenant_status_idx'), models.Index(fields=['tenant', 'currency'], name='pbk_tenant_currency_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('service', 'Service'), ('subscription', 'Subscription'), ('addon', 'Add-on'), ('bundle', 'Bundle')], default='software', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued'), ('draft', 'Draft')], default='active', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterdata_productcatalogs', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='pcat_tenant_status_idx'), models.Index(fields=['tenant', 'category'], name='pcat_tenant_category_idx')],
            },
        ),
    ]
