# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(blank=True, help_text='Rep or team this forecast belongs to.', max_length=120)),
                ('period_type', models.CharField(choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Annual')], default='quarter', max_length=20)),
                ('period_label', models.CharField(blank=True, help_text='e.g. Q3 2026.', max_length=40)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('pipeline_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Number the owner is committing to.', max_digits=14)),
                ('best_case_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ai_predicted_amount', models.DecimalField(decimal_places=2, default=0, help_text='AI/ML predicted close number.', max_digits=14)),
                ('ai_confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_forecasts', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, help_text='e.g. Q2 2026.', max_length=40)),
                ('forecasted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual minus forecasted (system-computed).', max_digits=14)),
                ('accuracy_pct', models.DecimalField(decimal_places=2, default=0, help_text='Accuracy score (%) for the period.', max_digits=6)),
                ('grade', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('analyzed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accuracy_records', to='forecasting.forecast')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_forecastaccuracys', to='core.tenant')),
            ],
            options={
                'ordering': ['-analyzed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('uplift', 'Uplift'), ('haircut', 'Haircut'), ('override', 'Override'), ('rollup', 'Roll-up')], default='uplift', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Signed delta applied to the forecast number.', max_digits=14)),
                ('adjusted_by', models.CharField(blank=True, help_text='Manager who made the adjustment.', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='forecasting.forecast')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_forecastadjustments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('commitment', models.CharField(choices=[('omitted', 'Omitted'), ('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('closed', 'Closed')], default='pipeline', max_length=20)),
                ('probability', models.PositiveIntegerField(default=50, help_text='Default win probability (%) for this category.')),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Roll-up weighting multiplier.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_forecastcategorys', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='forecast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='forecasting.forecastcategory'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text='Rep or team the quota is assigned to.', max_length=120)),
                ('period_type', models.CharField(choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Annual')], default='quarter', max_length=20)),
                ('period_label', models.CharField(blank=True, help_text='e.g. Q3 2026.', max_length=40)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attained_amount', models.DecimalField(decimal_places=2, default=0, help_text='Closed-won to date against this quota.', max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_quotas', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'owner_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('tenant', 'number')},
        ),
    ]
