# Generated by Django 5.1.15 on 2026-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['tenant', 'status'], name='fct_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['tenant', 'period_type'], name='fct_tenant_period_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['tenant', 'category'], name='fct_tenant_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastaccuracy',
            index=models.Index(fields=['tenant', 'grade'], name='facc_tenant_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastaccuracy',
            index=models.Index(fields=['tenant', 'analyzed_on'], name='facc_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastadjustment',
            index=models.Index(fields=['tenant', 'status'], name='fadj_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastadjustment',
            index=models.Index(fields=['tenant', 'adjustment_type'], name='fadj_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['tenant', 'status'], name='quota_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['tenant', 'period_type'], name='quota_tenant_period_idx'),
        ),
    ]
