# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_type', models.CharField(choices=[('web_form', 'Web form'), ('landing_page', 'Landing page'), ('referral', 'Referral'), ('event', 'Event'), ('paid_ads', 'Paid ads'), ('cold_outreach', 'Cold outreach'), ('partner', 'Partner')], default='web_form', max_length=20)),
                ('routing_rule', models.CharField(choices=[('round_robin', 'Round robin'), ('owner', 'Single owner'), ('team', 'Team queue'), ('manual', 'Manual review')], default='round_robin', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('default_owner', models.CharField(blank=True, max_length=120)),
                ('cost_per_lead', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_leadsources', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NurtureCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('social', 'Social'), ('multi', 'Multi-channel')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('step_count', models.PositiveIntegerField(default=1)),
                ('cadence_days', models.PositiveIntegerField(default=3)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('end_on', models.DateField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_nurturecampaigns', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('working', 'Working'), ('nurturing', 'Nurturing'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], default='new', max_length=20)),
                ('rating', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', max_length=10)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('captured_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_leads', to='core.tenant')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.nurturecampaign')),
            ],
            options={
                'ordering': ['-captured_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('outcome', models.CharField(choices=[('opportunity', 'Opportunity created'), ('account', 'Account created'), ('contact', 'Contact created'), ('disqualified', 'Disqualified')], default='opportunity', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('deal_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('handoff_notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_leadconversions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='leadconv_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(choices=[('A', 'A — Excellent'), ('B', 'B — Good'), ('C', 'C — Fair'), ('D', 'D — Poor')], default='C', max_length=2)),
                ('scoring_model', models.CharField(choices=[('rules', 'Rules-based'), ('predictive', 'Predictive (AI)'), ('manual', 'Manual')], default='rules', max_length=20)),
                ('demographic_points', models.IntegerField(default=0)),
                ('behavioral_points', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('scored_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_leadscores', to='core.tenant')),
            ],
            options={
                'ordering': ['-scored_on', '-score'],
                'indexes': [models.Index(fields=['tenant', 'grade'], name='leadscore_tenant_grade_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status'], name='lead_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'captured_on'], name='lead_tenant_captured_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('tenant', 'number')},
        ),
    ]
