# Generated by Django 5.1.15 on 2026-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['tenant', 'status'], name='leadsource_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['tenant', 'source_type'], name='leadsource_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='nurturecampaign',
            index=models.Index(fields=['tenant', 'status'], name='nurtcampaign_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nurturecampaign',
            index=models.Index(fields=['tenant', 'channel'], name='nurtcamp_tenant_channel_idx'),
        ),
    ]
