# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('advocacy_type', models.CharField(choices=[('reference', 'Reference'), ('case_study', 'Case study'), ('testimonial', 'Testimonial'), ('review', 'Review'), ('speaker', 'Speaker')], default='reference', max_length=20)),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('active', 'Active'), ('declined', 'Declined'), ('retired', 'Retired')], default='nominated', max_length=20)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('last_engaged', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_advocacies', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Advocacies',
                'ordering': ['account_name', 'contact_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='adv_tenant_status_idx'), models.Index(fields=['tenant', 'advocacy_type'], name='adv_tenant_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('score', models.IntegerField(default=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('arr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_reviewed', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_healthscores', to='core.tenant')),
            ],
            options={
                'ordering': ['-last_reviewed', 'account_name'],
                'indexes': [models.Index(fields=['tenant', 'risk_level'], name='hs_tenant_risk_idx'), models.Index(fields=['tenant', 'trend'], name='hs_tenant_trend_idx'), models.Index(fields=['tenant', 'last_reviewed'], name='hs_tenant_reviewed_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('plan_name', models.CharField(max_length=150)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_pct', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('target_go_live', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_onboardingplans', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', 'account_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='onb_tenant_status_idx'), models.Index(fields=['tenant', 'start_date'], name='onb_tenant_start_idx')],
            },
        ),
        migrations.CreateModel(
            name='QBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('period_label', models.CharField(max_length=60)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('scheduled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('health_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_qbrs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'QBR',
                'verbose_name_plural': 'QBRs',
                'ordering': ['-scheduled_on', 'account_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='qbr_tenant_status_idx'), models.Index(fields=['tenant', 'sentiment'], name='qbr_tenant_sentiment_idx'), models.Index(fields=['tenant', 'scheduled_on'], name='qbr_tenant_sched_idx')],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('renewal_type', models.CharField(choices=[('renewal', 'Renewal'), ('upsell', 'Upsell'), ('cross_sell', 'Cross-sell'), ('expansion', 'Expansion')], default='renewal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('at_risk', 'At risk'), ('committed', 'Committed'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=20)),
                ('arr_current', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('arr_proposed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('probability', models.IntegerField(default=50)),
                ('renewal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_renewals', to='core.tenant')),
            ],
            options={
                'ordering': ['-renewal_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='ren_tenant_status_idx'), models.Index(fields=['tenant', 'renewal_type'], name='ren_tenant_type_idx'), models.Index(fields=['tenant', 'renewal_date'], name='ren_tenant_date_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
