# Generated by Django 5.1.15 on 2026-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('success', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advocacy',
            index=models.Index(fields=['tenant', 'account_name'], name='adv_tenant_acct_idx'),
        ),
    ]
