# Generated by Django 5.1.15 on 2026-06-17 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_invoice_invoice_tenant_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsetting',
            name='accent_color',
            field=models.CharField(default='#0ea5e9', max_length=9, validators=[django.core.validators.RegexValidator('^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$', 'Enter a valid hex colour, e.g. #2563eb.')]),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=9, validators=[django.core.validators.RegexValidator('^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$', 'Enter a valid hex colour, e.g. #2563eb.')]),
        ),
    ]
