# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('slack', 'Slack'), ('webhook', 'Webhook')], default='email', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('trigger_condition', models.TextField(blank=True)),
                ('recipients', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_alertrules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='alr_tenant_status_idx'), models.Index(fields=['tenant', 'channel'], name='alr_tenant_channel_idx'), models.Index(fields=['tenant', 'severity'], name='alr_tenant_severity_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('approval_type', models.CharField(choices=[('discount', 'Discount'), ('quote', 'Quote'), ('contract', 'Contract'), ('expense', 'Expense'), ('deal', 'Deal'), ('refund', 'Refund')], default='discount', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('steps_count', models.IntegerField(default=1)),
                ('escalation_hours', models.IntegerField(default=24)),
                ('approvers', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_approvalworkflows', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='aw_tenant_status_idx'), models.Index(fields=['tenant', 'approval_type'], name='aw_tenant_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('entity', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('case', 'Case'), ('account', 'Account')], default='lead', max_length=20)),
                ('assign_strategy', models.CharField(choices=[('round_robin', 'Round robin'), ('load_balanced', 'Load balanced'), ('territory', 'Territory'), ('skill_based', 'Skill based'), ('manual', 'Manual')], default='round_robin', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('criteria', models.TextField(blank=True)),
                ('assignee_pool', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_assignmentrules', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='ar_tenant_status_idx'), models.Index(fields=['tenant', 'entity'], name='ar_tenant_entity_idx'), models.Index(fields=['tenant', 'assign_strategy'], name='ar_tenant_strategy_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data_source', models.CharField(choices=[('clearbit', 'Clearbit'), ('zoominfo', 'ZoomInfo'), ('linkedin', 'LinkedIn'), ('internal', 'Internal'), ('manual', 'Manual')], default='internal', max_length=20)),
                ('operation', models.CharField(choices=[('enrich', 'Enrich'), ('dedupe', 'Dedupe'), ('normalize', 'Normalize'), ('validate', 'Validate'), ('append', 'Append')], default='enrich', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('target_field', models.CharField(blank=True, max_length=120)),
                ('records_processed', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_enrichmentrules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='er_tenant_status_idx'), models.Index(fields=['tenant', 'data_source'], name='er_tenant_source_idx'), models.Index(fields=['tenant', 'operation'], name='er_tenant_operation_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trigger_event', models.CharField(choices=[('record_created', 'Record created'), ('record_updated', 'Record updated'), ('stage_changed', 'Stage changed'), ('field_changed', 'Field changed'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='record_created', max_length=20)),
                ('object_type', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('account', 'Account'), ('quote', 'Quote'), ('order', 'Order')], default='lead', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('steps_count', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_processflows', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='pf_tenant_status_idx'), models.Index(fields=['tenant', 'trigger_event'], name='pf_tenant_trigger_idx'), models.Index(fields=['tenant', 'object_type'], name='pf_tenant_object_idx')],
            },
        ),
    ]
