from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.dashboard.urls")),
    path("auth/", include("apps.accounts.urls")),
    path("core/", include("apps.core.urls")),
    path("tenant/", include("apps.tenants.urls")),
    path("leads/", include("apps.leads.urls")),
    path("opportunities/", include("apps.opportunities.urls")),
    path("crm/", include("apps.crm.urls")),
    path("forecasting/", include("apps.forecasting.urls")),
    path("quotes/", include("apps.quotes.urls")),
    path("orders/", include("apps.orders.urls")),
    path("territories/", include("apps.territories.urls")),
    path("activities/", include("apps.activities.urls")),
    path("enablement/", include("apps.enablement.urls")),
    path("compensation/", include("apps.compensation.urls")),
    path("success/", include("apps.success.urls")),
    path("analytics/", include("apps.analytics.urls")),
    path("marketing/", include("apps.marketing.urls")),
    path("partners/", include("apps.partners.urls")),
    path("contracts/", include("apps.contracts.urls")),
    path("mobile/", include("apps.mobile.urls")),
    path("automation/", include("apps.automation.urls")),
    path("integrations/", include("apps.integrations.urls")),
    path("masterdata/", include("apps.masterdata.urls")),
    path("administration/", include("apps.administration.urls")),
]
