# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150)),
                ('model_type', models.CharField(choices=[('first_touch', 'First touch'), ('last_touch', 'Last touch'), ('linear', 'Linear'), ('time_decay', 'Time decay'), ('w_shaped', 'W-shaped')], default='linear', max_length=20)),
                ('influenced_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('opportunities_count', models.IntegerField(default=0)),
                ('attribution_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period_label', models.CharField(max_length=60)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigninfluences', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', 'campaign_name'],
                'indexes': [models.Index(fields=['tenant', 'model_type'], name='ci_tenant_modeltype_idx'), models.Index(fields=['tenant', 'recorded_on'], name='ci_tenant_recdate_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('paid_search', 'Paid search'), ('social', 'Social'), ('webinar', 'Webinar'), ('event', 'Event'), ('content', 'Content'), ('direct', 'Direct')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('leads_generated', models.IntegerField(default=0)),
                ('revenue_influenced', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaignperformances', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', 'campaign_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='cperf_tenant_status_idx'), models.Index(fields=['tenant', 'channel'], name='cperf_tenant_channel_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=150)),
                ('content_type', models.CharField(choices=[('blog', 'Blog post'), ('whitepaper', 'Whitepaper'), ('video', 'Video'), ('webinar', 'Webinar'), ('case_study', 'Case study'), ('ebook', 'eBook'), ('datasheet', 'Datasheet')], default='blog', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('avg_time_seconds', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_contentengagements', to='core.tenant')),
            ],
            options={
                'ordering': ['-published_on', 'content_title'],
                'indexes': [models.Index(fields=['tenant', 'content_type'], name='ce_tenant_ctype_idx'), models.Index(fields=['tenant', 'published_on'], name='ce_tenant_pubdate_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('webinar', 'Webinar'), ('conference', 'Conference'), ('trade_show', 'Trade show'), ('workshop', 'Workshop'), ('virtual', 'Virtual')], default='webinar', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('registration_open', 'Registration open'), ('live', 'Live'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='planned', max_length=20)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('registrations', models.IntegerField(default=0)),
                ('attendees', models.IntegerField(default=0)),
                ('leads_captured', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_marketingevents', to='core.tenant')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='evt_tenant_status_idx'), models.Index(fields=['tenant', 'event_type'], name='evt_tenant_etype_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MQLHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('lead_name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('mql_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('mql', 'MQL'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('sql', 'SQL'), ('recycled', 'Recycled')], default='mql', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('handed_to', models.CharField(blank=True, max_length=120)),
                ('handoff_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_mqlhandoffs', to='core.tenant')),
            ],
            options={
                'ordering': ['-handoff_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='mql_tenant_status_idx'), models.Index(fields=['tenant', 'handoff_date'], name='mql_tenant_handdate_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
