# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('segment', models.CharField(choices=[('strategic', 'Strategic'), ('enterprise', 'Enterprise'), ('mid_market', 'Mid-Market'), ('smb', 'SMB'), ('startup', 'Startup')], default='mid_market', max_length=20)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Lower ranks sort first (Tier 1 = 1).')),
                ('min_annual_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('color', models.CharField(default='#2563eb', max_length=9)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_accounttiers', to='core.tenant')),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('account_type', models.CharField(choices=[('prospect', 'Prospect'), ('customer', 'Customer'), ('partner', 'Partner'), ('reseller', 'Reseller'), ('competitor', 'Competitor')], default='prospect', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('churned', 'Churned')], default='active', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('billing_city', models.CharField(blank=True, max_length=120)),
                ('billing_country', models.CharField(blank=True, max_length=120)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_accounts', to='core.tenant')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='crm.accounttier')),
            ],
            options={
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('bounced', 'Bounced')], default='active', max_length=20)),
                ('enrichment_status', models.CharField(choices=[('none', 'Not enriched'), ('partial', 'Partial'), ('verified', 'Verified')], default='none', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='core.tenant')),
            ],
            options={
                'ordering': ['last_name', 'first_name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('reports_to', 'Reports to'), ('influences', 'Influences'), ('sponsor', 'Sponsor'), ('blocker', 'Blocker'), ('peer', 'Peer')], default='reports_to', max_length=20)),
                ('strength', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], default='moderate', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_maps', to='crm.account')),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_relationshipmaps', to='core.tenant')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('fiscal_year', models.PositiveIntegerField(default=2026)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_track', 'On track'), ('at_risk', 'At risk'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('objective', models.TextField(blank=True)),
                ('growth_strategy', models.TextField(blank=True)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_plans', to='crm.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_accountplans', to='core.tenant')),
            ],
            options={
                'ordering': ['-fiscal_year', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='crm_plan_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'status'], name='crm_acct_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'account_type'], name='crm_acct_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'status'], name='crm_contact_tenant_status_idx'),
        ),
    ]
