# Generated by Django 5.1.15 on 2026-06-18 17:40

import apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountplan',
            name='fiscal_year',
            field=models.PositiveIntegerField(default=apps.crm.models._current_year),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'tier'], name='crm_acct_tenant_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='accountplan',
            index=models.Index(fields=['tenant', 'account'], name='crm_plan_tenant_account_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttier',
            index=models.Index(fields=['tenant', 'segment'], name='crm_tier_tenant_segment_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'account'], name='crm_contact_tenant_account_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipmap',
            index=models.Index(fields=['tenant', 'account'], name='crm_relmap_tenant_account_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipmap',
            index=models.Index(fields=['tenant', 'relationship_type'], name='crm_relmap_tenant_type_idx'),
        ),
    ]
