# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_type', models.CharField(choices=[('direct', 'Direct field'), ('inside', 'Inside sales'), ('hybrid', 'Hybrid'), ('partner', 'Partner / channel'), ('pod', 'Pod / team-based')], default='direct', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pilot', 'Pilot'), ('adopted', 'Adopted'), ('retired', 'Retired')], default='proposed', max_length=20)),
                ('target_ratio', models.DecimalField(decimal_places=2, default=0, help_text='Accounts per rep (coverage ratio).', max_digits=6)),
                ('rep_capacity', models.PositiveIntegerField(default=0)),
                ('coverage_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories_coveragemodels', to='core.tenant')),
            ],
            options={
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('territory_type', models.CharField(choices=[('geographic', 'Geographic'), ('industry', 'Industry / Vertical'), ('account', 'Account Size'), ('product', 'Product Line'), ('named_account', 'Named Account')], default='geographic', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under review'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('account_count', models.PositiveIntegerField(default=0)),
                ('annual_potential', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories_territorys', to='core.tenant')),
            ],
            options={
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TerritoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=150)),
                ('rep_email', models.EmailField(blank=True, max_length=254)),
                ('assignment_role', models.CharField(choices=[('owner', 'Primary owner'), ('overlay', 'Overlay specialist'), ('backup', 'Backup / cover'), ('manager', 'Manager')], default='owner', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('rebalancing', 'Rebalancing'), ('ended', 'Ended')], default='proposed', max_length=20)),
                ('workload_percent', models.PositiveIntegerField(default=100)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories_territoryassignments', to='core.tenant')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='territories.territory')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TerritoryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='quarterly', max_length=20)),
                ('period_label', models.CharField(blank=True, max_length=40)),
                ('rating', models.CharField(choices=[('exceeding', 'Exceeding'), ('on_track', 'On track'), ('at_risk', 'At risk'), ('underperforming', 'Underperforming')], default='on_track', max_length=20)),
                ('quota_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attainment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pipeline_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deals_won', models.PositiveIntegerField(default=0)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories_territoryperformances', to='core.tenant')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='territories.territory')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='quarterly', max_length=20)),
                ('fiscal_year', models.PositiveIntegerField(default=2026)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stretch_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories_quotaplans', to='core.tenant')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_plans', to='territories.territory')),
            ],
            options={
                'ordering': ['-fiscal_year', '-id'],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
