# Generated by Django 5.1.15 on 2026-06-18 17:41

import apps.territories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotaplan',
            name='fiscal_year',
            field=models.PositiveIntegerField(default=apps.territories.models._current_year),
        ),
        migrations.AddIndex(
            model_name='coveragemodel',
            index=models.Index(fields=['tenant', 'status'], name='cm_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragemodel',
            index=models.Index(fields=['tenant', 'model_type'], name='cm_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaplan',
            index=models.Index(fields=['tenant', 'status'], name='qp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaplan',
            index=models.Index(fields=['tenant', 'territory'], name='qp_tenant_territory_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaplan',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='qp_tenant_fy_idx'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['tenant', 'status'], name='terr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['tenant', 'territory_type'], name='terr_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryassignment',
            index=models.Index(fields=['tenant', 'status'], name='ta_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryassignment',
            index=models.Index(fields=['tenant', 'territory'], name='ta_tenant_territory_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryperformance',
            index=models.Index(fields=['tenant', 'territory'], name='tp_tenant_territory_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryperformance',
            index=models.Index(fields=['tenant', 'rating'], name='tp_tenant_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryperformance',
            index=models.Index(fields=['tenant', 'period_end'], name='tp_tenant_period_idx'),
        ),
    ]
