# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('differential', 'Differential'), ('snapshot', 'Snapshot')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retention_days', models.IntegerField(default=30)),
                ('scheduled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_backupjobs', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='bkp_tenant_status_idx'), models.Index(fields=['tenant', 'backup_type'], name='bkp_tenant_type_idx'), models.Index(fields=['tenant', 'scheduled_on'], name='bkp_tenant_scheddate_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('framework', models.CharField(choices=[('gdpr', 'GDPR'), ('soc2', 'SOC 2'), ('iso27001', 'ISO 27001'), ('hipaa', 'HIPAA'), ('pci_dss', 'PCI DSS')], default='soc2', max_length=20)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant'), ('in_progress', 'In progress'), ('not_applicable', 'Not applicable')], default='in_progress', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_audited', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_complianceitems', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='cmpl_tenant_status_idx'), models.Index(fields=['tenant', 'framework'], name='cmpl_tenant_fw_idx'), models.Index(fields=['tenant', 'severity'], name='cmpl_tenant_sev_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataPrivacyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('regulation', models.CharField(choices=[('gdpr', 'GDPR'), ('ccpa', 'CCPA'), ('hipaa', 'HIPAA'), ('sox', 'SOX'), ('pci_dss', 'PCI DSS'), ('internal', 'Internal')], default='gdpr', max_length=20)),
                ('data_category', models.CharField(choices=[('pii', 'PII'), ('financial', 'Financial'), ('health', 'Health'), ('contact', 'Contact'), ('behavioral', 'Behavioral')], default='pii', max_length=20)),
                ('action', models.CharField(choices=[('retain', 'Retain'), ('anonymize', 'Anonymize'), ('delete', 'Delete'), ('encrypt', 'Encrypt'), ('restrict', 'Restrict')], default='retain', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('retention_days', models.IntegerField(default=365)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_dataprivacyrules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='dpr_tenant_status_idx'), models.Index(fields=['tenant', 'regulation'], name='dpr_tenant_reg_idx'), models.Index(fields=['tenant', 'data_category'], name='dpr_tenant_cat_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('policy_type', models.CharField(choices=[('password', 'Password'), ('mfa', 'Multi-factor auth'), ('session', 'Session'), ('ip_allowlist', 'IP allowlist'), ('data_retention', 'Data retention'), ('access_control', 'Access control')], default='password', max_length=20)),
                ('status', models.CharField(choices=[('enforced', 'Enforced'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('scope', models.CharField(choices=[('all_users', 'All users'), ('admins', 'Admins'), ('tenant', 'Tenant'), ('role', 'Role')], default='all_users', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_securitypolicys', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='secpol_tenant_status_idx'), models.Index(fields=['tenant', 'policy_type'], name='secpol_tenant_type_idx'), models.Index(fields=['tenant', 'severity'], name='secpol_tenant_sev_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Memory'), ('disk', 'Disk'), ('database', 'Database'), ('api', 'API'), ('uptime', 'Uptime'), ('response_time', 'Response time')], default='cpu', max_length=20)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='healthy', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('percent', 'Percent'), ('ms', 'Milliseconds'), ('gb', 'Gigabytes'), ('count', 'Count')], default='percent', max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_systemhealthmetrics', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', 'metric_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='shm_tenant_status_idx'), models.Index(fields=['tenant', 'category'], name='shm_tenant_cat_idx'), models.Index(fields=['tenant', 'recorded_on'], name='shm_tenant_recdate_idx')],
            },
        ),
    ]
