# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to order')], default='draft', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_quotes', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template', models.CharField(choices=[('standard', 'Standard'), ('executive', 'Executive summary'), ('technical', 'Technical deep-dive'), ('minimal', 'Minimal')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('final', 'Final'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('executive_summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=150)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_proposals', to='core.tenant')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='quotes.quote')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('hour', 'Hour'), ('month', 'Month'), ('year', 'Year'), ('license', 'License')], default='each', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_quotelineitems', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('change_type', models.CharField(choices=[('initial', 'Initial version'), ('price_change', 'Price change'), ('scope_change', 'Scope change'), ('discount_change', 'Discount change'), ('terms_change', 'Terms change')], default='initial', max_length=20)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_current', models.BooleanField(default=False)),
                ('snapshot_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.quote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_quoteversions', to='core.tenant')),
            ],
            options={
                'ordering': ['quote', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('rule_type', models.CharField(choices=[('volume', 'Volume discount'), ('promotional', 'Promotional'), ('loyalty', 'Loyalty'), ('contract', 'Contract'), ('clearance', 'Clearance')], default='volume', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('min_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approval_level', models.CharField(choices=[('auto', 'Auto-approved'), ('manager', 'Manager approval'), ('director', 'Director approval'), ('vp', 'VP approval')], default='auto', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_pricingrules', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='pricerule_tenant_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'status'], name='quote_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'created_at'], name='quote_tenant_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['tenant', 'status'], name='proposal_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quotelineitem',
            index=models.Index(fields=['tenant', 'quote'], name='qli_tenant_quote_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteversion',
            index=models.Index(fields=['tenant', 'quote'], name='qver_tenant_quote_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteversion',
            unique_together={('quote', 'version_number')},
        ),
    ]
