# Generated by Django 5.1.15 on 2026-06-17 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('rep_name', models.CharField(max_length=120)),
                ('coach_name', models.CharField(blank=True, max_length=120)),
                ('call_type', models.CharField(choices=[('discovery', 'Discovery'), ('demo', 'Demo'), ('negotiation', 'Negotiation'), ('check_in', 'Check-in'), ('closing', 'Closing')], default='discovery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed'), ('coached', 'Coached'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('recording_url', models.URLField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coaching_notes', models.TextField(blank=True)),
                ('call_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablement_callrecordings', to='core.tenant')),
            ],
            options={
                'ordering': ['-call_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('overview', models.TextField(blank=True)),
                ('our_strengths', models.TextField(blank=True, help_text='Where we win.')),
                ('their_strengths', models.TextField(blank=True, help_text='Where they win.')),
                ('objection_handling', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('last_updated_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablement_competitivecards', to='core.tenant')),
            ],
            options={
                'ordering': ['competitor_name'],
            },
        ),
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('asset_type', models.CharField(choices=[('deck', 'Pitch Deck'), ('one_pager', 'One-Pager'), ('case_study', 'Case Study'), ('whitepaper', 'Whitepaper'), ('video', 'Video'), ('template', 'Template'), ('other', 'Other')], default='deck', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords for search.', max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablement_contentassets', to='core.tenant')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('discovery', 'Discovery'), ('demo', 'Demo'), ('negotiation', 'Negotiation'), ('closing', 'Closing'), ('onboarding', 'Onboarding')], default='prospecting', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('persona', models.CharField(blank=True, help_text='Target buyer persona.', max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('guidance', models.TextField(blank=True, help_text='The plays, talk tracks and next steps.')),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablement_playbooks', to='core.tenant')),
            ],
            options={
                'ordering': ['stage', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=180)),
                ('rep_name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('course', 'Course'), ('certification', 'Certification'), ('workshop', 'Workshop'), ('onboarding', 'Onboarding')], default='course', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('enrolled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablement_trainingrecords', to='core.tenant')),
            ],
            options={
                'ordering': ['-enrolled_on', '-id'],
            },
        ),
    ]
