# Generated by Django 5.1.15 on 2026-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
        ('enablement', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['tenant', 'status'], name='cr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['tenant', 'call_type'], name='cr_tenant_calltype_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['tenant', 'call_date'], name='cr_tenant_calldate_idx'),
        ),
        migrations.AddIndex(
            model_name='competitivecard',
            index=models.Index(fields=['tenant', 'status'], name='cc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='competitivecard',
            index=models.Index(fields=['tenant', 'threat_level'], name='cc_tenant_threat_idx'),
        ),
        migrations.AddIndex(
            model_name='contentasset',
            index=models.Index(fields=['tenant', 'status'], name='ca_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contentasset',
            index=models.Index(fields=['tenant', 'asset_type'], name='ca_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='playbook',
            index=models.Index(fields=['tenant', 'status'], name='pb_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='playbook',
            index=models.Index(fields=['tenant', 'stage'], name='pb_tenant_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['tenant', 'status'], name='tr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['tenant', 'kind'], name='tr_tenant_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['tenant', 'enrolled_on'], name='tr_tenant_enrolled_idx'),
        ),
    ]
