# Generated by Django 5.1.15 on 2026-06-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_auditlog_tenant_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('win_rate', 'Win rate'), ('cycle_time', 'Cycle time'), ('deal_size', 'Deal size'), ('quota_attainment', 'Quota attainment'), ('activity', 'Activity')], default='win_rate', max_length=20)),
                ('our_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('peer_median', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_quartile', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('period_label', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('above', 'Above peers'), ('at', 'At par'), ('below', 'Below peers')], default='at', max_length=20)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_benchmarks', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', 'metric_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='bm_tenant_status_idx'), models.Index(fields=['tenant', 'category'], name='bm_tenant_category_idx'), models.Index(fields=['tenant', 'recorded_on'], name='bm_tenant_recorded_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=120)),
                ('segment', models.CharField(choices=[('enterprise', 'Enterprise'), ('midmarket', 'Mid-market'), ('smb', 'SMB'), ('all', 'All segments')], default='all', max_length=20)),
                ('period_label', models.CharField(max_length=60)),
                ('entered_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_days_in_stage', models.IntegerField(default=0)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_conversionfunnels', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'segment'], name='cf_tenant_segment_idx'), models.Index(fields=['tenant', 'recorded_on'], name='cf_tenant_recorded_idx')],
            },
        ),
        migrations.CreateModel(
            name='RepScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=120)),
                ('period_label', models.CharField(max_length=60)),
                ('quota', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attainment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('deals_won', models.IntegerField(default=0)),
                ('deals_lost', models.IntegerField(default=0)),
                ('activities', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('a', 'A — Outstanding'), ('b', 'B — Strong'), ('c', 'C — Meets'), ('d', 'D — Below')], default='c', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_repscorecards', to='core.tenant')),
            ],
            options={
                'ordering': ['ranking', '-attainment', 'rep_name'],
                'indexes': [models.Index(fields=['tenant', 'grade'], name='rsc_tenant_grade_idx'), models.Index(fields=['tenant', 'ranking'], name='rsc_tenant_ranking_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=60)),
                ('segment', models.CharField(choices=[('enterprise', 'Enterprise'), ('midmarket', 'Mid-market'), ('smb', 'SMB'), ('all', 'All segments')], default='all', max_length=20)),
                ('avg_deal_size', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sales_cycle_days', models.IntegerField(default=0)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('velocity_score', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_salesvelocitys', to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'segment'], name='sv_tenant_segment_idx'), models.Index(fields=['tenant', 'recorded_on'], name='sv_tenant_recorded_idx')],
            },
        ),
        migrations.CreateModel(
            name='WinLossAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=150)),
                ('rep_name', models.CharField(max_length=120)),
                ('outcome', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('no_decision', 'No decision')], default='won', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('competitor', models.CharField(blank=True, max_length=120)),
                ('reason_category', models.CharField(choices=[('price', 'Price'), ('product', 'Product fit'), ('relationship', 'Relationship'), ('timing', 'Timing'), ('features', 'Features'), ('other', 'Other')], default='price', max_length=20)),
                ('closed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_winlossanalysises', to='core.tenant')),
            ],
            options={
                'ordering': ['-closed_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'outcome'], name='wla_tenant_outcome_idx'), models.Index(fields=['tenant', 'reason_category'], name='wla_tenant_reason_idx'), models.Index(fields=['tenant', 'closed_on'], name='wla_tenant_closed_idx')],
            },
        ),
    ]
